# 1.Print 'Hello HCIA'.

In [1]:
print ('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [2]:
a=3
b=169
c=a+b
print(c)

172


# 3.Define a list and replicate in three different ways.

In [4]:
import copy
list1 = [1,2,3,4,5]
n_list = copy.copy(list1)
print(n_list)
n_list = list1
print(n_list)
print(list1)
print(list1[:])
n_list = list1[:]
print(list1)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


# 4.Define two lists and merge them together.

In [11]:
a= list (range(10))
b= list (range(1,20,2))
print (a)
print(b)
c=a+b
print (c)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


# 5. Get the last element of the list and print it.

In [13]:
print(c[19])

19


# 6.Define a tuple that contains only one element.

In [ ]:
a=tuple(range(1))
print(a)

# 7.Define a three-line long string.

In [2]:
c = '''это очень большая
... строка, многострочный
... блок текста'''
print(c)

это очень большая
строка, многострочный
блок текста


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [3]:
a=tuple(range(4,15,2))
for i in range (0,6,1):
 print(a[i])

4
6
8
10
12
14


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [6]:
def func(x,y):
    return x*y
print (func(21,40))

840


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [5]:
import numpy as np 
np.zeros ((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [6]:
import numpy as np
np.zeros ((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [1]:
import numpy as np
a= np.arange (15)
print(a)
a=np.arange(15).reshape(3,5)
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [2]:
import numpy as np
A=np.arange(8).reshape(2,4)
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
import numpy as np
B=np.arange(8).reshape(4,2)
B


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [5]:
import numpy as np
np.matmul(A,B)

array([[28, 34],
       [76, 98]])